kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: patrickstigler/youtube-transcript-to-article
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - ${DRONE_COMMIT_BRANCH}
      - latest
