version: '3'
services:
  youtube-transcript-to-article:
    image: patrickstigler/youtube-transcript-to-article
    container_name: youtube_transcript_to_article    
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}    
    ports:
      - "5000:5000"
